_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.9.7
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.7
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-x86_64
architecture:
    value: NN
dataset:
    value: MNIST
epochs:
    value: 10
learning_rate:
    value: 0.05
